name = "DaggerAppsBenchmarks"
uuid = "e06dd71a-ed03-4e2f-bbc0-1e61969572cf"
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"

[sources]
Dagger = {url = "https://github.com/JuliaParallel/Dagger.jl", rev = "fda/sc26-ad"}
